const achievements = {
  "Beginner Bookie": {
    url: "https://i.ibb.co/NZGCQZc/badge1-Photo-Room.png",
    description: "Achieved by logging your first book. Good job!",
    title: "Beginner Bookie",
    height: "200px",
    width: "200px",
  },
  "Apprentice Bookkeeper": {
    url: "https://i.ibb.co/5W5THS8/badge2-polished-Photo-Room.png",
    description: "Achieved by reading more than one book in a month.",
    title: "Apprentice Bookkeeper",
    height: "180px",
    width: "180px",
  },
  "Pagemaster in Training": {
    url: "https://i.ibb.co/p1xyXPg/badge3-Photo-Room.png",
    description: "Achieved by reading over 500 pages.",
    title: "Pagemaster in Training",
    height: "200px",
    width: "200px",
  },
  "Certified Book Fiend": {
    url: "https://i.ibb.co/sPvHdZm/badge4-Photo-Room.png",
    description: "Achieved by reading for three months straight.",
    title: "Certified Book Fiend",
    height: "200px",
    width: "200px",
  },
  "Grand Pagemaster": {
    url: "https://i.ibb.co/t2RdVsC/badge5-polished-Photo-Room-Photo-Room.png",
    description: "Achieved by reading over 1,000 pages.",
    title: "Grand Pagemaster",
    height: "200px",
    width: "200px",
  },
  "January 2024": {
    url: "https://i.ibb.co/S7wzDMg/badge-jan-Photo-Room.png",
    description: "Achieved by reaching your reading goal for January 2024.",
    title: "January 2024",
    height: "200px",
    width: "200px",
  },
  "February 2024": {
    url: "https://i.ibb.co/0snPYJZ/badge-feb-Photo-Room.png",
    description: "Achieved by reaching your reading goal for February 2024.",
    title: "February 2024",
    height: "200px",
    width: "200px",
  },
  "March 2024": {
    url: "https://i.ibb.co/qk0JZ46/badge-mar-Photo-Room.png",
    description: "Achieved by reaching your reading goal for March 2024.",
    title: "March 2024",
    height: "200px",
    width: "200px",
  },
  "April 2024": {
    url: "https://i.ibb.co/F8LyQMj/badge-apr-Photo-Room.png",
    description: "Achieved by reaching your reading goal for April 2024.",
    title: "April 2024",
    height: "200px",
    width: "200px",
  },
  "May 2024": {
    url: "https://i.ibb.co/ZgLPHXC/badge-may-Photo-Room.png",
    description: "Achieved by reaching your reading goal for May 2024.",
    title: "May 2024",
    height: "200px",
    width: "200px",
  },
  "June 2024": {
    url: "https://i.ibb.co/rG5JW4q/badge-june-polished-Photo-Room2.png",
    description: "Achieved by reaching your reading goal for June 2024.",
    title: "June 2024",
    height: "200px",
    width: "200px",
  },
  "July 2024": {
    url: "https://i.ibb.co/j8tGn3d/badge-jul-Photo-Room.png",
    description: "Achieved by reaching your reading goal for July 2024.",
    title: "July 2024",
    height: "200px",
    width: "200px",
  },
  "August 2024": {
    url: "https://i.ibb.co/pKbmVxb/badge-aug-Photo-Room.png",
    description: "Achieved by reaching your reading goal for August 2024.",
    title: "August 2024",
    height: "200px",
    width: "200px",
  },
  "September 2024": {
    url: "https://i.ibb.co/YLXhnRB/badge-sep-Photo-Room.png",
    description: "Achieved by reaching your reading goal for September 2024.",
    title: "September 2024",
    height: "200px",
    width: "200px",
  },
  "October 2024": {
    url: "https://i.ibb.co/cDbmMXK/badge-oct-polished-Photo-Room.png",
    description: "Achieved by reaching your reading goal for October 2024.",
    title: "October 2024",
    height: "200px",
    width: "200px",
  },
  "November 2024": {
    url: "https://i.ibb.co/ftvQfs9/badge-nov-Photo-Room.png",
    description: "Achieved by reaching your reading goal for November 2024.",
    title: "November 2024",
    height: "200px",
    width: "200px",
  },
  "December 2024": {
    url: "https://i.ibb.co/qpBqCd3/badge-dec-Photo-Room.png",
    description: "Achieved by reaching your reading goal for December 2024.",
    title: "December 2024",
    height: "200px",
    width: "200px",
  },
};

export default achievements;
